# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './WebApplication1/*.sln'
  buildPlataform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Instal .Net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Restore Solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"
  displayName: 'Test Solution'  

- script: |
    echo "Conteúdo do diretório atual:"
    ls -R
  displayName: "Listar arquivos no agente"

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'Connection -ACR-APIDEMO'
    repository: 'api-dio-test'
    command: 'buildAndPush'
    Dockerfile: './WebApplication1/WebApplication1/Dockerfile'
    buildContext: './WebApplication1/WebApplication1'